export const defaultStarships = [
  {
    name: "CR90 corvette",
    model: "CR90 corvette",
    manufacturer: "Corellian Engineering Corporation",
    default_cost_in_credits: 3500000,
    max_atmosphering_speed: "950",
    passengers: "600",
    cargo_capacity: "3000000",
    starship_class: "corvette",
    img: "https://static.wikia.nocookie.net/starwars/images/2/24/TantiveIV-TSWB.png/revision/latest?cb=20221006055135",
  },
  {
    name: "Star Destroyer",
    model: "Imperial I-class Star Destroyer",
    manufacturer: "Kuat Drive Yards",
    default_cost_in_credits: 150000000,
    max_atmosphering_speed: "975",
    passengers: "n/a",
    cargo_capacity: "36000000",
    starship_class: "Star Destroyer",
    img: "https://static.wikia.nocookie.net/starwars/images/e/e4/ImperialClassStarDestroyer-TSWB.png/revision/latest?cb=20230515235250",
  },
  {
    name: "Sentinel-class landing craft",
    model: "Sentinel-class landing craft",
    manufacturer: "Sienar Fleet Systems, Cyngus Spaceworks",
    default_cost_in_credits: 240000,
    max_atmosphering_speed: "1000",
    passengers: "75",
    cargo_capacity: "180000",
    starship_class: "landing craft",
    img: "https://static.wikia.nocookie.net/starwars/images/6/6e/Sentinel_negvv.png/revision/latest?cb=20170411232732",
  },
  {
    name: "Death Star",
    model: "DS-1 Orbital Battle Station",
    manufacturer:
      "Imperial Department of Military Research, Sienar Fleet Systems",
    default_cost_in_credits: 1000000000000,
    max_atmosphering_speed: "n/a",
    passengers: "843342",
    cargo_capacity: "1000000000000",
    starship_class: "Deep Space Mobile Battlestation",
    img: "https://static.wikia.nocookie.net/starwars/images/7/70/DSI-HDapproach.png/revision/latest?cb=20130221005853",
  },
  {
    name: "Millennium Falcon",
    model: "YT-1300 light freighter",
    manufacturer: "Corellian Engineering Corporation",
    default_cost_in_credits: 100000,
    max_atmosphering_speed: "1050",
    passengers: "6",
    cargo_capacity: "100000",
    starship_class: "Light freighter",
    img: "https://static.wikia.nocookie.net/starwars/images/5/52/Millennium_Falcon_Fathead_TROS.png/revision/latest?cb=20221029015218",
  },
  {
    name: "Y-wing",
    model: "BTL Y-wing",
    manufacturer: "Koensayr Manufacturing",
    default_cost_in_credits: 134999,
    max_atmosphering_speed: "1000km",
    passengers: "0",
    cargo_capacity: "110",
    starship_class: "assault starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/8/81/Y-wing.png/revision/latest?cb=20161110013308",
  },
  {
    name: "X-wing",
    model: "T-65 X-wing",
    manufacturer: "Incom Corporation",
    default_cost_in_credits: 149999,
    max_atmosphering_speed: "1050",
    passengers: "0",
    cargo_capacity: "110",
    starship_class: "Starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/0/00/Xwing-ROOCE.png/revision/latest?cb=20230516042654",
  },
  {
    name: "TIE Advanced x1",
    model: "Twin Ion Engine Advanced x1",
    manufacturer: "Sienar Fleet Systems",
    default_cost_in_credits: 180000,
    max_atmosphering_speed: "1200",
    passengers: "0",
    cargo_capacity: "150",
    starship_class: "Starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/1/1d/Vader_TIEAdvanced_SWB.png/revision/latest?cb=20160915042032",
  },
  {
    name: "Executor",
    model: "Executor-class star dreadnought",
    manufacturer: "Kuat Drive Yards, Fondor Shipyards",
    default_cost_in_credits: 1143350000,
    max_atmosphering_speed: "n/a",
    passengers: "38000",
    cargo_capacity: "250000000",
    starship_class: "Star dreadnought",
    img: "https://static.wikia.nocookie.net/starwars/images/3/30/Executor_BF2.png/revision/latest?cb=20230405071103",
  },
  {
    name: "Rebel transport",
    model: "GR-75 medium transport",
    manufacturer: "Gallofree Yards, Inc.",
    default_cost_in_credits: 260000,
    max_atmosphering_speed: "650",
    passengers: "90",
    cargo_capacity: "19000000",
    starship_class: "Medium transport",
    img: "https://static.wikia.nocookie.net/starwars/images/4/44/GR-75MediumTransport-100Scenes.png/revision/latest?cb=20221105213502",
  },
  {
    name: "Slave 1",
    model: "Firespray-31-class patrol and attack",
    manufacturer: "Kuat Systems Engineering",
    default_cost_in_credits: 120000,
    max_atmosphering_speed: "1000",
    passengers: "6",
    cargo_capacity: "70000",
    starship_class: "Patrol craft",
    img: "https://static.wikia.nocookie.net/starwars/images/b/ba/Slave_I_DICE.png/revision/latest?cb=20230723041624",
  },
  {
    name: "Imperial shuttle",
    model: "Lambda-class T-4a shuttle",
    manufacturer: "Sienar Fleet Systems",
    default_cost_in_credits: 240000,
    max_atmosphering_speed: "850",
    passengers: "20",
    cargo_capacity: "80000",
    starship_class: "Armed government transport",
    img: "https://static.wikia.nocookie.net/starwars/images/6/6d/LambdaShuttle-Fathead.png/revision/latest?cb=20230802043430",
  },
  {
    name: "EF76 Nebulon-B escort frigate",
    model: "EF76 Nebulon-B escort frigate",
    manufacturer: "Kuat Drive Yards",
    default_cost_in_credits: 8500000,
    max_atmosphering_speed: "800",
    passengers: "75",
    cargo_capacity: "6000000",
    starship_class: "Escort ship",
    img: "https://static.wikia.nocookie.net/starwars/images/7/71/NebulonB-SWS.png/revision/latest?cb=20210303023412",
  },
  {
    name: "Calamari Cruiser",
    model: "MC80 Liberty type Star Cruiser",
    manufacturer: "Mon Calamari shipyards",
    default_cost_in_credits: 104000000,
    max_atmosphering_speed: "n/a",
    passengers: "1200",
    cargo_capacity: "unknown",
    starship_class: "Star Cruiser",
    img: "https://static.wikia.nocookie.net/starwars/images/7/73/MonCalamariCruiser-TSWB.png/revision/latest?cb=20201021040315",
  },
  {
    name: "A-wing",
    model: "RZ-1 A-wing Interceptor",
    manufacturer: "Alliance Underground Engineering, Incom Corporation",
    default_cost_in_credits: 175000,
    max_atmosphering_speed: "1300",
    passengers: "0",
    cargo_capacity: "40",
    starship_class: "Starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/8/8d/A-wing_DICE.png/revision/latest?cb=20161021230115",
  },
  {
    name: "B-wing",
    model: "A/SF-01 B-wing starfighter",
    manufacturer: "Slayn & Korpil",
    default_cost_in_credits: 220000,
    max_atmosphering_speed: "950",
    passengers: "0",
    cargo_capacity: "45",
    starship_class: "Assault Starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/9/9f/B-wing-Squadronds.png/revision/latest?cb=20210722003428",
  },
  {
    name: "Republic Cruiser",
    model: "Consular-class cruiser",
    manufacturer: "Corellian Engineering Corporation",
    default_cost_in_credits: 220000,
    max_atmosphering_speed: "900",
    passengers: "16",
    cargo_capacity: "unknown",
    starship_class: "Space cruiser",
    img: "https://static.wikia.nocookie.net/starwars/images/5/5f/Republic_Cruiser.png/revision/latest?cb=20230311200333",
  },
  {
    name: "Droid control ship",
    model: "Lucrehulk-class Droid Control Ship",
    manufacturer: "Hoersch-Kessel Drive, Inc.",
    default_cost_in_credits: 150000000,
    max_atmosphering_speed: "n/a",
    passengers: "139000",
    cargo_capacity: "4000000000",
    starship_class: "Droid control ship",
    img: "https://static.wikia.nocookie.net/starwars/images/9/95/Lucrehulk_battleship_TCW.jpg/revision/latest?cb=20090311015214",
  },
  {
    name: "Naboo fighter",
    model: "N-1 starfighter",
    manufacturer: "Theed Palace Space Vessel Engineering Corps",
    default_cost_in_credits: 200000,
    max_atmosphering_speed: "1100",
    passengers: "0",
    cargo_capacity: "65",
    starship_class: "Starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/4/4f/DinDjarinN1-BHUSC.png/revision/latest?cb=20221205013955",
  },
  {
    name: "Naboo Royal Starship",
    model: "J-type 327 Nubian royal starship",
    manufacturer:
      "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
    default_cost_in_credits: 450000,
    max_atmosphering_speed: "920",
    passengers: "unknown",
    cargo_capacity: "unknown",
    starship_class: "yacht",
    img: "https://static.wikia.nocookie.net/starwars/images/8/88/Nabooroyal-NEGVV.png/revision/latest?cb=20170411041529",
  },
  {
    name: "Scimitar",
    model: "Star Courier",
    manufacturer: "Republic Sienar Systems",
    default_cost_in_credits: 55000000,
    max_atmosphering_speed: "1180",
    passengers: "6",
    cargo_capacity: "2500000",
    starship_class: "Space Transport",
    img: "https://static.wikia.nocookie.net/starwars/images/1/1c/Scimitar-USC.png/revision/latest?cb=20190604143506",
  },
  {
    name: "J-type diplomatic barge",
    model: "J-type diplomatic barge",
    manufacturer:
      "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
    default_cost_in_credits: 2000000,
    max_atmosphering_speed: "2000",
    passengers: "10",
    cargo_capacity: "unknown",
    starship_class: "Diplomatic barge",
    img: "https://static.wikia.nocookie.net/starwars/images/2/2b/Royalcruiser.jpg/revision/latest?cb=20091201140703",
  },
  {
    name: "AA-9 Coruscant freighter",
    model: "Botajef AA-9 Freighter-Liner",
    manufacturer: "Botajef Shipyards",
    default_cost_in_credits: 450000,
    max_atmosphering_speed: "unknown",
    passengers: "30000",
    cargo_capacity: "unknown",
    starship_class: "freighter",
    img: "https://static.wikia.nocookie.net/starwars/images/c/c7/Aa9coruscantfreighter.jpg/revision/latest?cb=20091201131352",
  },
  {
    name: "Jedi starfighter",
    model: "Delta-7 Aethersprite-class interceptor",
    manufacturer: "Kuat Systems Engineering",
    default_cost_in_credits: 180000,
    max_atmosphering_speed: "1150",
    passengers: "0",
    cargo_capacity: "60",
    starship_class: "Starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/2/28/Delta-7_Interceptor_SoR.png/revision/latest?cb=20180805054640",
  },
  {
    name: "H-type Nubian yacht",
    model: "H-type Nubian yacht",
    manufacturer: "Theed Palace Space Vessel Engineering Corps",
    default_cost_in_credits: 430000,
    max_atmosphering_speed: "8000",
    passengers: "unknown",
    cargo_capacity: "unknown",
    starship_class: "yacht",
    img: "https://static.wikia.nocookie.net/starwars/images/8/87/H-Type_Nubian_yacht_USW.png/revision/latest?cb=20230709053810",
  },
  {
    name: "Republic Assault ship",
    model: "Acclamator I-class assault ship",
    manufacturer: "Rothana Heavy Engineering",
    default_cost_in_credits: 1050000,
    max_atmosphering_speed: "unknown",
    passengers: "16000",
    cargo_capacity: "11250000",
    starship_class: "assault ship",
    img: "https://static.wikia.nocookie.net/starwars/images/7/70/Acclamator-TCWIV.png/revision/latest?cb=20221105061503",
  },
  {
    name: "Solar Sailer",
    model: "Punworcca 116-class interstellar sloop",
    manufacturer: "Huppla Pasa Tisc Shipwrights Collective",
    default_cost_in_credits: 35700,
    max_atmosphering_speed: "1600",
    passengers: "11",
    cargo_capacity: "240",
    starship_class: "yacht",
    img: "https://static.wikia.nocookie.net/starwars/images/1/10/CountDookusSolarSailer-WotF.png/revision/latest?cb=20200518063614",
  },
  {
    name: "Trade Federation cruiser",
    model: "Providence-class carrier/destroyer",
    manufacturer: "Rendili StarDrive, Free Dac Volunteers Engineering corps.",
    default_cost_in_credits: 125000000,
    max_atmosphering_speed: "1050",
    passengers: "48247",
    cargo_capacity: "50000000",
    starship_class: "capital ship",
    img: "https://static.wikia.nocookie.net/battlefront/images/1/17/Providence-Class.png/revision/latest?cb=20110910180110",
  },
  {
    name: "Theta-class T-2c shuttle",
    model: "Theta-class T-2c shuttle",
    manufacturer: "Cygnus Spaceworks",
    default_cost_in_credits: 1000000,
    max_atmosphering_speed: "2000",
    passengers: "16",
    cargo_capacity: "50000",
    starship_class: "transport",
    img: "https://static.wikia.nocookie.net/starwars/images/7/71/Theta.jpg/revision/latest?cb=20060405185857",
  },
  {
    name: "Republic attack cruiser",
    model: "Senator-class Star Destroyer",
    manufacturer: "Kuat Drive Yards, Allanteen Six shipyards",
    default_cost_in_credits: 59000000,
    max_atmosphering_speed: "975",
    passengers: "2000",
    cargo_capacity: "20000000",
    starship_class: "star destroyer",
    img: "https://static.wikia.nocookie.net/starwars/images/e/ec/Venator_clonewars.jpg/revision/latest?cb=20110918171254",
  },
  {
    name: "Naboo star skiff",
    model: "J-type star skiff",
    manufacturer:
      "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated",
    default_cost_in_credits: 150000,
    max_atmosphering_speed: "1050",
    passengers: "3",
    cargo_capacity: "unknown",
    starship_class: "yacht",
    img: "https://static.wikia.nocookie.net/starwars/images/1/1f/Nabooskiff-SWCTP.png/revision/latest?cb=20221031044447",
  },
  {
    name: "Jedi Interceptor",
    model: "Eta-2 Actis-class light interceptor",
    manufacturer: "Kuat Systems Engineering",
    default_cost_in_credits: 320000,
    max_atmosphering_speed: "1500",
    passengers: "0",
    cargo_capacity: "60",
    starship_class: "starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/0/04/Eta-2JediInterceptor-USC.png/revision/latest?cb=20190604144353",
  },
  {
    name: "arc-170",
    model: "Aggressive Reconnaissance-170 starfighte",
    manufacturer: "Incom Corporation, Subpro Corporation",
    default_cost_in_credits: 155000,
    max_atmosphering_speed: "1000",
    passengers: "0",
    cargo_capacity: "110",
    starship_class: "starfighter",
    img: "https://static.wikia.nocookie.net/thelastofthedroids/images/0/02/ARC170.png/revision/latest?cb=20180802180836",
  },
  {
    name: "Banking clan frigte",
    model: "Munificent-class star frigate",
    manufacturer: "Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries",
    default_cost_in_credits: 57000000,
    max_atmosphering_speed: "unknown",
    passengers: "unknown",
    cargo_capacity: "40000000",
    starship_class: "cruiser",
    img: "https://static.wikia.nocookie.net/starwars/images/0/07/Munificent_TCW.jpg/revision/latest?cb=20090311013715",
  },
  {
    name: "Belbullab-22 starfighter",
    model: "Belbullab-22 starfighter",
    manufacturer: "Feethan Ottraw Scalable Assemblies",
    default_cost_in_credits: 168000,
    max_atmosphering_speed: "1100",
    passengers: "0",
    cargo_capacity: "140",
    starship_class: "starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/8/8c/SoullessOne-TCWIV.png/revision/latest?cb=20221105045811",
  },
  {
    name: "V-wing",
    model: "Alpha-3 Nimbus-class V-wing starfighter",
    manufacturer: "Kuat Systems Engineering",
    default_cost_in_credits: 102500,
    max_atmosphering_speed: "1050",
    passengers: "0",
    cargo_capacity: "60",
    starship_class: "starfighter",
    img: "https://static.wikia.nocookie.net/starwars/images/a/a9/V-wing_BF2.png/revision/latest?cb=20170825000555",
  },
];
